#ifndef SCRABBLE_CONSTANTS_H
#define SCRABBLE_CONSTANTS_H

#define SCRABBLE_ALPHABET_SIZE 26
#define SCRABBLE_BOARD_SIZE 15
#define SCRABBLE_BOARD_CENTER_INDEX (SCRABBLE_BOARD_SIZE / 2)
#define SCRABBLE_RACK_CAPACITY 7
#define SCRABBLE_MAX_WORD_LENGTH 15

#endif
